DATASET:
  BATCH_SIZE: 32
  CROP_FACTOR: 0.5
  CROP_PROB: 0.2
  DATASETS_AND_RATIOS: 'zoom-suburbd'
  MESH_COLOR: pinkish
  NOISE_FACTOR: 0.4
  NUM_WORKERS: 4
  PIN_MEMORY: true
  SCALE_FACTOR: 0.25
  SHUFFLE_TRAIN: true
  VAL_DS: 3dpw-test-cam
  CROP_PERCENT: 0.8
  ALB: true
EXP_NAME: bedlam_cam_ready
LOG_DIR: logs
OPTIMIZER:
  LR: 5e-5
  TYPE: adamw
  WD: 5e-5
MODEL:
  BACKBONE: sd2_0
  BETA_LOSS_WEIGHT: 0.001
  JOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_LOSS_WEIGHT: 5.0
  LOSS_WEIGHT: 60.0
  POSE_LOSS_WEIGHT: 1.0
  SHAPE_LOSS_WEIGHT: 1.0
TESTING:
  FP_VIS: true
  MESH_VIS: false
TRAINING:
  CHECK_VAL_EVERY_N_EPOCH: 1
  MAX_EPOCHS: 200000
  PRETRAINED_CKPT: coco
  PRETRAINED_LIT: null
  RELOAD_DATALOADERS_EVERY_EPOCH: false
  RESUME: null
  TEST_BEFORE_TRAINING: false
  WP_VIS: false
  FP_VIS: false
TRIAL:
  bedlam_bbox: true
  criterion: mse
